### ISSUE TITLE
Please update nuget packages

### ISSUE THREAD

**Issue by maratbakirov** [andrei-markeev/camljs#20]
Hi.
I am using groupby and aggregations and i have noticed that they are not supporter yet in the latest online  nuget package with the typoescript definitions... 

https://www.nuget.org/packages/camljs.TypeScript.DefinitelyTyped/

thank you!

**Comment by andrei-markeev** [comment]
Definitions are now updated on DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33209#issuecomment-466116173

However, turns out that DefinitelyTyped stopped pubishing typings to Nuget a while ago (back in 2016), so please switch to `npm i @types/camljs` or use camljs.d.ts from the [release files](https://github.com/andrei-markeev/camljs/releases).
