### ISSUE TITLE
CamlBuilder.All breaks the source array of expressions.

### ISSUE THREAD

**Issue by maratbakirov** [andrei-markeev/camljs#21]
I was crating a search ui and dynamically generated an array of expressions.
The generated array of expressions was stored in the variable. 

so something like

           this.expressions = GenerateExpressions(); (should be at least two of them)
            var allAuditsCamlBuilder1 = new CamlBuilder()
                .View(["ID", "Created"])
                .RowLimit(pageSize, true)
                .Scope(CamlBuilder.ViewScope.RecursiveAll).Query().Where()

            var allAuditsCamlBuilder = allAuditsCamlBuilder1.All(this.expressions);
            var allAudits = allAuditsCamlBuilder.ToString();

  then i was implementing paging so i was using the same array of expressions.
            var allAuditsCamlBuilder = allAuditsCamlBuilder1.All(this.expressions);
            var allAudits = allAuditsCamlBuilder.ToString();

and the caml query had an extra outside And.

so what happens is that the expressions are getting changed after the All and then ToString() calls, so i had to regenerate them each time.

**Comment by maratbakirov** [comment]
here is the caml query i got the first time 
caml query : <View Scope="RecursiveAll"><ViewFields><FieldRef Name="ID" /><FieldRef Name="Created" /></ViewFields><RowLimit Paged="TRUE">10</RowLimit><Query> <Where><And><Geq><FieldRef Name="Created" /><Value IncludeTimeValue="True" Type="DateTime">2008-12-31T15:00:00.000Z</Value></Geq><Leq><FieldRef Name="Created" /><Value IncludeTimeValue="True" Type="DateTime">2020-01-01T16:00:00.000Z</Value></Leq></And></Where></Query></View>


here is the one i got a second time

caml query : <View Scope="RecursiveAll"><ViewFields><FieldRef Name="ID" /><FieldRef Name="Created" /></ViewFields><RowLimit Paged="TRUE">10</RowLimit><Query> <Where><And><And><Geq><FieldRef Name="Created" /><Value IncludeTimeValue="True" Type="DateTime">2008-12-31T15:00:00.000Z</Value></Geq><Leq><FieldRef Name="Created" /><Value IncludeTimeValue="True" Type="DateTime">2020-01-01T16:00:00.000Z</Value></Leq></And></And></Where></Query>


note the extra opening and closing And that made the caml query invalid.

**Comment by maratbakirov** [comment]
might be related to #14

**Comment by andrei-markeev** [comment]
Thanks for reporting, will look into this soon!

**Comment by andrei-markeev** [comment]
Issue happens because **CamlBuilder** is stateful, so you cannot really reuse it to produce several queries, rather, you would need to create a new **CamlBuilder** for each query. So after you call `ToString()` or `ToCamlQuery()`, the builder shouldn't be used anymore.

So what happened in your particular case, you essentially did something like this:
```js
new CamlBuilder()
        .View(["ID", "Created"])
        .RowLimit(pageSize, true)
       .Scope(CamlBuilder.ViewScope.RecursiveAll).Query().Where()
       .All(this.expressions)
       .All(this.expressions) // notice the duplicate "All", this is of course invalid
       .ToString();
```

For now, I am planning to add a check so that people aren't getting confused and will get some human-friendly error message instead of silently getting a potentially incorrect query.

There's of course an option to make a deep copy of the state every time when returning the object in every chain call, but it is quite bad for performance.
