### ISSUE TITLE
Support ToString() when page is loading

### ISSUE THREAD

**Issue by vitsko** [andrei-markeev/camljs#35]
Hello,

1. I use various queries, not only this:

```
$(function (){
var query = new CamlBuilder().Where().LookupField("fieldName").Id().EqualTo(1).ToString()
});
```

2. Result is:
![image](https://user-images.githubusercontent.com/26853273/99071844-58e6aa00-25cc-11eb-9716-6a5ff2875d51.png)

3.  Could you please explain workaround to use CamlBuilder with ToString() when page is loading? Or maybe is it a bug?

Thanks.

**Comment by andrei-markeev** [comment]
If there's a global object `Sys` on the page (part of MS Ajax library), CamlJs tries to use `Sys.StringBuilder`.
Otherwise, it polyfills it:
```js
(function (window) {
    if (typeof (window["Sys"]) == "undefined" || window["Sys"] == null) {
        window["Sys"] = {};
        window["Sys"].StringBuilder = function Sys$StringBuilder(initialText) {
    //...
```
Looks like you have `Sys` on the page, but `Sys.StringBuilder` is missing or not yet loaded by the time the script is executed.

What you can try to troubleshoot:
Open your page, wait until it fully loads, open DevTools and run `Sys.StringBuilder` in the console.
1. If it prints `undefined`, then probably you need to patch CamlJs to always polyfill Sys.StringBuilder
2. If it shows that such object exists, then this most likely means that you need to wait a bit and run your CamlJs query a bit later, when StringBuilder is loaded

**Comment by vitsko** [comment]
I took advantage of second way.
"If it shows that such object exists, then this most likely means that you need to wait a bit and run your CamlJs query a bit later, when StringBuilder is loaded"

 Thanks a lot of your reply.
